In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("danielrosehill/iran-israel-war-2026")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/danielrosehill/iran-israel-war-2026?dataset_version_number=11...

100%|██████████| 114k/114k [00:00<00:00, 68.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/danielrosehill/iran-israel-war-2026/versions/11

In [3]:
!ls /root/.cache/kagglehub/datasets/danielrosehill/iran-israel-war-2026/versions/11

data_dictionary.csv	     international_reactions.parquet  waves.parquet
international_reactions.csv  waves.csv

In [5]:
cp /root/.cache/kagglehub/datasets/danielrosehill/iran-israel-war-2026/versions/11/*.* .

In [6]:
!ls -ilah

total 344K
3145734 drwxr-xr-x 1 root root 4.0K Mar  9 14:04 .
6291472 drwxr-xr-x 1 root root 4.0K Mar  9 14:02 ..
2883591 drwxr-xr-x 4 root root 4.0K Jan 16 14:24 .config
6296294 -rw-r--r-- 1 root root  14K Mar  9 14:04 data_dictionary.csv
6296295 -rw-r--r-- 1 root root  58K Mar  9 14:04 international_reactions.csv
6296296 -rw-r--r-- 1 root root  49K Mar  9 14:04 international_reactions.parquet
3145735 drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data
6296297 -rw-r--r-- 1 root root  90K Mar  9 14:04 waves.csv
6296298 -rw-r--r-- 1 root root 106K Mar  9 14:04 waves.parquet

In [7]:
!cat data_dictionary.csv

column_name,data_type,nullable,description
wave_uid,string,no,"Unique wave identifier for cross-layer joins (e.g. 'tp4_w21')"
operation,string,no,"Operation identifier: tp1 (Apr 2024), tp2 (Oct 2024), tp3 (Jun 2025), tp4 (Feb 2026+)"
wave_number,integer,no,Sequential wave number within the operation (1-indexed)
wave_codename_farsi,string,yes,Iranian codename for this wave in Farsi script
wave_codename_english,string,yes,Iranian codename for this wave transliterated to English
announced_utc,datetime,yes,ISO 8601 timestamp (UTC) when wave was first announced or detected
announcement_source,string,yes,"Source of the first announcement (e.g. IDF, IRGC, OSINT account)"
probable_launch_time,datetime,yes,ISO 8601 timestamp of estimated launch time based on OSINT analysis
launch_time_israel,string,yes,Local launch time in Israel Standard Time (IST/IDT)
launch_time_iran,string,yes,Local launch time in Iran Standard Time (IRST/IRDT)
solar_phase_launch_site,integer,yes,"Solar illumination at launch site: 0=Night, 1=Astronomical twilight, 2=Nautical twilight, 3=Civil twilight, 4=Low sun, 5=Daylight"
solar_phase_target,integer,yes,"Solar illumination at target: 0=Night, 1=Astronomical twilight, 2=Nautical twilight, 3=Civil twilight, 4=Low sun, 5=Daylight"
conflict_day,integer,yes,Day number of the conflict (Day 1 = first wave of that operation)
hours_since_last_wave,float,yes,Hours elapsed since the previous wave in the same operation
time_between_waves_minutes,float,yes,Minutes elapsed since the previous wave (finer granularity than hours_since_last_wave)
wave_duration_minutes,float,yes,Estimated duration of the wave from first to last munition arrival
payload,string,yes,"Free-text description of the weapon payload composition (e.g. 'mixed BM + drones', 'ballistic only')"
drones_used,boolean,yes,Whether UAVs/loitering munitions were used in this wave
ballistic_missiles_used,boolean,yes,Whether ballistic missiles were used in this wave
cruise_missiles_used,boolean,yes,Whether cruise missiles were used in this wave
emad_used,boolean,yes,Whether Emad liquid-fueled MRBM was used
ghadr_used,boolean,yes,Whether Ghadr liquid-fueled MRBM was used
sejjil_used,boolean,yes,Whether Sejjil solid-fueled MRBM was used
kheibar_shekan_used,boolean,yes,Whether Kheibar Shekan solid-fueled MRBM was used
fattah_used,boolean,yes,Whether Fattah-1 or Fattah-2 hypersonic missile was used
shahed_136_used,boolean,yes,Whether Shahed-136 one-way attack drone was used
shahed_238_used,boolean,yes,Whether Shahed-238 jet-powered one-way attack drone was used
shahed_131_used,boolean,yes,Whether Shahed-131 one-way attack drone was used
shahed_107_used,boolean,yes,Whether Shahed-107 (Ababil-2) drone was used
shahed_129_used,boolean,yes,Whether Shahed-129 MALE UCAV was used
mohajer_6_used,boolean,yes,Whether Mohajer-6 reconnaissance/strike UCAV was used
bm_liquid_fueled,boolean,yes,Whether any liquid-fueled ballistic missile was used in this wave
bm_solid_fueled,boolean,yes,Whether any solid-fueled ballistic missile was used in this wave
bm_marv_equipped,boolean,yes,Whether any MARV-equipped (maneuverable reentry vehicle) ballistic missile was used
bm_hypersonic,boolean,yes,Whether any hypersonic-class ballistic missile (Mach 5+) was used
bm_cluster_warhead,boolean,yes,Whether any ballistic missile carried cluster submunitions
cluster_munitions,boolean,yes,"Derived: true if cluster warhead confirmed for this wave (from weapons.cluster_warhead)"
cluster_warhead_confirmed,boolean,yes,Whether cluster warhead use was confirmed by IDF/police/OSINT evidence
cluster_carrier_missile,string,yes,"Missile type that delivered the cluster warhead (e.g. 'Fattah-2')"
cluster_submunition_count,integer,yes,Estimated number of submunitions per cluster warhead
cluster_submunition_explosive_kg,float,yes,Explosive weight per individual submunition in kilograms
cluster_dispersal_radius_km,float,yes,Estimated dispersal radius of submunitions in kilometers
israel_targeted,boolean,yes,Whether this wave targeted locations in Israel
us_bases_targeted,boolean,yes,Whether this wave targeted US military bases in the region
targets,string,yes,"Free-text description of targets (e.g. 'Nevatim Airbase, Ramon Airbase')"
landings_countries_iso,string,yes,"Comma-separated ISO 3166-1 alpha-2 country codes where munitions landed (e.g. 'IL, JO, PS')"
landings_countries,string,yes,"Comma-separated readable country names where munitions landed (e.g. 'Israel, Jordan, Palestine')"
targeted_tel_aviv,boolean,yes,Whether Tel Aviv / Gush Dan metropolitan area was targeted
targeted_jerusalem,boolean,yes,Whether Jerusalem area was targeted
targeted_haifa,boolean,yes,Whether Haifa / northern coast was targeted
targeted_negev_beersheba,boolean,yes,Whether Negev desert / Beersheba area was targeted (includes Nevatim/Ramon airbases)
targeted_northern_periphery,boolean,yes,Whether northern periphery (Galilee / Golan) was targeted
targeted_eilat,boolean,yes,Whether Eilat / southernmost Israel was targeted
us_bases_list,string,yes,"Comma-separated names of US military bases targeted (e.g. 'Al Udeid Air Base, Al Dhafra Air Base')"
us_naval_vessels_list,string,yes,"Comma-separated names of US naval vessels targeted (e.g. 'USS Eisenhower, USS Philippine Sea')"
target_lat,float,yes,Latitude of primary target in decimal degrees (WGS84)
target_lon,float,yes,Longitude of primary target in decimal degrees (WGS84)
target_generic_location,boolean,yes,"Whether target coordinates are an approximate centroid (true) or specifically geolocated (false/null)"
target_iaf_base,boolean,yes,"Derived: whether this wave targeted an Israeli Air Force base (Nevatim, Ramon, Tel Nof, Hatzerim, Ramat David, Ovda)"
target_us_base,boolean,yes,"Derived: whether this wave targeted a US/coalition military base"
target_naval_base,boolean,yes,"Derived: whether this wave targeted a naval base or port facility"
target_naval_vessel,boolean,yes,"Derived: whether this wave targeted a naval vessel at sea"
target_government_c2,boolean,yes,"Derived: whether this wave targeted a government HQ, ministry, or C2 node"
target_military_industrial,boolean,yes,"Derived: whether this wave targeted defense industry or military production facilities"
target_intelligence,boolean,yes,"Derived: whether this wave targeted intelligence facilities (CIA, Mossad, Unit 8200, radar)"
target_civilian_infrastructure,boolean,yes,"Derived: whether this wave targeted civilian infrastructure (airports, refineries, power plants, data centres)"
target_civilian_area,boolean,yes,"Derived: whether this wave targeted or struck residential/civilian areas"
target_diplomatic,boolean,yes,"Derived: whether this wave targeted diplomatic facilities (embassies, consulates)"
launch_site_description,string,yes,"Free-text description of launch origin (e.g. 'Western Iran, Kermanshah province')"
launch_site_lat,float,yes,Latitude of launch site in decimal degrees (WGS84)
launch_site_lon,float,yes,Longitude of launch site in decimal degrees (WGS84)
launch_site_generic_location,boolean,yes,"Whether launch site coordinates are an approximate centroid (true) or specifically geolocated (false/null)"
intercepted,boolean,yes,Whether any munitions from this wave were intercepted
interception_systems,string,yes,"Comma-separated defense systems used (e.g. 'Arrow-2, Arrow-3, David's Sling, Iron Dome')"
intercepted_by_israel,boolean,yes,Whether Israel participated in interception of this wave
intercepted_by_us,boolean,yes,Whether the United States participated in interception of this wave
intercepted_by_uk,boolean,yes,Whether the United Kingdom participated in interception of this wave
intercepted_by_jordan,boolean,yes,Whether Jordan participated in interception of this wave
intercepted_by_other,string,yes,Comma-separated names of other countries that participated in interception
estimated_intercept_count,integer,yes,Estimated number of munitions intercepted in this wave
estimated_intercept_rate,float,yes,Estimated interception rate as a decimal (0.0-1.0) for this wave
exoatmospheric_interception,boolean,yes,Whether exoatmospheric (above atmosphere ~100km) interceptions occurred
endoatmospheric_interception,boolean,yes,Whether endoatmospheric (within atmosphere) interceptions occurred
interception_report,string,yes,Free-text summary of interception activity and outcomes
estimated_munitions_count,integer,yes,Estimated total number of munitions (missiles + drones) fired in this wave
munitions_targeting_israel,integer,yes,Number of munitions in this wave directed at Israeli targets
munitions_targeting_us_bases,integer,yes,Number of munitions in this wave directed at US military bases
cumulative_total,integer,yes,Running cumulative total of all munitions fired across all waves in this operation
small_number_of_missiles,boolean,yes,Flag indicating a small/token salvo rather than a full wave
damage,string,yes,Free-text description of damage caused by this wave
fatalities,integer,yes,Total number of fatalities (military + civilian) caused by this wave
injuries,integer,yes,Total number of injuries (military + civilian) caused by this wave
civilian_casualties,integer,yes,Number of civilian casualties (killed + injured) from this wave
military_casualties,integer,yes,Number of military casualties (killed + injured) from this wave
new_country_targeted,boolean,yes,Whether this wave targeted a country not previously attacked in this operation (escalation marker)
new_weapon_first_use,boolean,yes,Whether this wave introduced a weapon system not previously used in this operation (escalation marker)
proxy_involvement,boolean,yes,"Whether proxy forces (e.g. Hezbollah, Houthis, Iraqi militias) were involved in this wave"
proxy_description,string,yes,Free-text description of proxy force involvement
description,string,yes,Free-text narrative summary of the wave
iranian_media_claims,string,yes,JSON-encoded Iranian state media claims about this wave's results
idf_statement,string,yes,Summary or excerpt of official IDF statement regarding this wave
source_urls,string,yes,Comma-separated URLs of OSINT sources documenting this wave
narrative,string,yes,"1-2 paragraph analytical description of the wave's tactical significance, targeting, and context"
,,,"--- International Reactions (international_reactions.csv / .parquet) ---"
operation,string,no,"Operation identifier: tp4 (Feb 2026+); will expand as reactions data is added for earlier operations"
iso_3166_1_alpha2,string,yes,"ISO 3166-1 alpha-2 country code (e.g. US, IR, IL); null for multilateral entities"
entity_name,string,no,"Country or organisation name (e.g. 'United States', 'European Union', 'NATO')"
entity_type,string,no,"Entity classification: 'state' or 'multilateral'"
eu_member_state,boolean,no,Whether the entity is a current EU member state
combatant,boolean,no,Whether the entity is an active participant (combatant) in the conflict
overall_stance,string,no,"Categorical stance: active_participant_coalition, active_participant_pro_iran, supports_israel, condemns_iran, calls_for_deescalation, neutral_acknowledgement, supports_iran, condemns_israel, silent"
hos_statement_made,boolean,yes,Whether the head of state issued a public statement
hos_date,datetime,yes,ISO 8601 date of the head of state's statement
hos_speaker,string,yes,Name of the head of state who made the statement
hos_speaker_title,string,yes,"Title of the speaker (e.g. 'President', 'King', 'Supreme Leader')"
hos_summary,string,yes,Brief summary of the head of state's statement
hos_statement_text,string,yes,Full or partial text of the statement
hos_statement_url,string,yes,URL source for the head of state's statement
hos_category,string,yes,"Statement tone category (e.g. 'condemnation', 'support', 'concern')"
hog_statement_made,boolean,yes,Whether the head of government issued a public statement
hog_date,datetime,yes,ISO 8601 date of the head of government's statement
hog_speaker,string,yes,Name of the head of government who made the statement
hog_speaker_title,string,yes,"Title of the speaker (e.g. 'Prime Minister', 'Chancellor')"
hog_summary,string,yes,Brief summary of the head of government's statement
hog_statement_text,string,yes,Full or partial text of the statement
hog_statement_url,string,yes,URL source for the head of government's statement
hog_category,string,yes,"Statement tone category (e.g. 'condemnation', 'support', 'concern')"
fm_statement_made,boolean,yes,Whether the foreign ministry issued a public statement
fm_date,datetime,yes,ISO 8601 date of the foreign ministry's statement
fm_speaker,string,yes,Name of the foreign ministry spokesperson or minister
fm_speaker_title,string,yes,"Title of the speaker (e.g. 'Foreign Minister', 'Spokesperson')"
fm_summary,string,yes,Brief summary of the foreign ministry's statement
fm_statement_text,string,yes,Full or partial text of the statement
fm_statement_url,string,yes,URL source for the foreign ministry's statement
fm_category,string,yes,"Statement tone category (e.g. 'condemnation', 'support', 'concern')"
additional_statements_count,integer,no,Number of additional statements beyond the three standard channels
additional_statements_json,string,yes,"JSON array of additional statements (each with speaker, title, summary, url, category)"
notes,string,yes,Free-text contextual notes about the entity's position and relevant background

In [8]:
ls *.csv

data_dictionary.csv  international_reactions.csv  waves.csv

In [10]:
import pandas as pd

df_dict = pd.read_csv('data_dictionary.csv')
df_dict.head()

,column_name,data_type,nullable,description
0,wave_uid,string,no,Unique wave identifier for cross-layer joins (...
1,operation,string,no,"Operation identifier: tp1 (Apr 2024), tp2 (Oct..."
2,wave_number,integer,no,Sequential wave number within the operation (1...
3,wave_codename_farsi,string,yes,Iranian codename for this wave in Farsi script
4,wave_codename_english,string,yes,Iranian codename for this wave transliterated ...

In [12]:
dfw = pd.read_csv('waves.csv')
dfw.head()

,wave_uid,operation,wave_number,wave_codename_farsi,wave_codename_english,announced_utc,announcement_source,probable_launch_time,launch_time_israel,launch_time_iran,...,target_us_base,target_naval_base,target_naval_vessel,target_government_c2,target_military_industrial,target_intelligence,target_civilian_infrastructure,target_civilian_area,target_diplomatic,narrative
0,tp1_w01,tp1,1,NaN,Drone/Cruise Missile Wave,2024-04-13T19:00:00Z,IRGC,2024-04-13T19:00:00Z,2024-04-13T22:00:00+0300,2024-04-13T22:30:00+0330,...,False,False,False,False,False,False,False,False,False,The first wave of Iran's inaugural direct atta...
1,tp1_w02,tp1,2,NaN,Ballistic Missile Wave,NaN,NaN,2024-04-13T23:00:00Z,2024-04-14T02:00:00+0300,2024-04-14T02:30:00+0330,...,False,False,False,False,False,False,False,False,False,"The second and final wave of True Promise 1, c..."
2,tp2_w01,tp2,1,NaN,First Ballistic Salvo,2024-10-01T16:30:00Z,IRGC,2024-10-01T16:30:00Z,2024-10-01T19:30:00+0300,2024-10-01T20:00:00+0330,...,False,False,False,False,False,False,False,False,False,True Promise 2 opened with a ballistic-missile...
3,tp2_w02,tp2,2,NaN,Second Ballistic Salvo (Fattah-1),NaN,NaN,2024-10-01T16:45:00Z,2024-10-01T19:45:00+0300,2024-10-01T20:15:00+0330,...,False,False,False,True,False,True,False,False,False,The second wave of TP2 targeted the Mossad/Uni...
4,tp3_w01,tp3,1,NaN,NaN,2025-06-13T18:30:00Z,IRGC,2025-06-13T18:30:00Z,2025-06-13T21:30:00+0300,2025-06-14T00:00:00+0330,...,False,False,False,False,False,False,False,False,False,The opening salvo of the Twelve-Day War. Launc...

Warning: Total number of columns (103) exceeds max_columns (20) limiting to first (20) columns.

In [19]:
pd.set_option('display.max_columns', None)
dfw.head(10)

,wave_uid,operation,wave_number,wave_codename_farsi,wave_codename_english,announced_utc,announcement_source,probable_launch_time,launch_time_israel,launch_time_iran,solar_phase_launch_site,solar_phase_target,conflict_day,hours_since_last_wave,time_between_waves_minutes,wave_duration_minutes,payload,drones_used,ballistic_missiles_used,cruise_missiles_used,emad_used,ghadr_used,sejjil_used,kheibar_shekan_used,fattah_used,shahed_136_used,shahed_238_used,shahed_131_used,shahed_107_used,shahed_129_used,mohajer_6_used,bm_liquid_fueled,bm_solid_fueled,bm_marv_equipped,bm_hypersonic,bm_cluster_warhead,cluster_munitions,cluster_warhead_confirmed,cluster_carrier_missile,cluster_submunition_count,cluster_submunition_explosive_kg,cluster_dispersal_radius_km,israel_targeted,us_bases_targeted,targets,landings_countries_iso,landings_countries,targeted_tel_aviv,targeted_jerusalem,targeted_haifa,targeted_negev_beersheba,targeted_northern_periphery,targeted_eilat,us_bases_list,us_naval_vessels_list,target_lat,target_lon,target_generic_location,launch_site_description,launch_site_lat,launch_site_lon,launch_site_generic_location,intercepted,interception_systems,intercepted_by_israel,intercepted_by_us,intercepted_by_uk,intercepted_by_jordan,intercepted_by_other,estimated_intercept_count,estimated_intercept_rate,exoatmospheric_interception,endoatmospheric_interception,interception_report,estimated_munitions_count,munitions_targeting_israel,munitions_targeting_us_bases,cumulative_total,small_number_of_missiles,damage,fatalities,injuries,civilian_casualties,military_casualties,new_country_targeted,new_weapon_first_use,proxy_involvement,proxy_description,description,iranian_media_claims,idf_statement,source_urls,target_iaf_base,target_us_base,target_naval_base,target_naval_vessel,target_government_c2,target_military_industrial,target_intelligence,target_civilian_infrastructure,target_civilian_area,target_diplomatic,narrative
0,tp1_w01,tp1,1,NaN,Drone/Cruise Missile Wave,2024-04-13T19:00:00Z,IRGC,2024-04-13T19:00:00Z,2024-04-13T22:00:00+0300,2024-04-13T22:30:00+0330,0.0,0.0,1,NaN,NaN,NaN,170 Shahed-136 loitering munitions and 30 Pave...,True,False,True,False,False,False,False,False,True,False,NaN,NaN,NaN,NaN,False,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Nevatim Airbase, sites in Negev desert and Isr...",IL,Israel,False,False,False,True,True,False,NaN,NaN,30.890,34.780,False,Multiple sites across Iran; Shahed drones also...,33.00,52.00,False,True,"Iron Dome, David's Sling, Patriot PAC-3, Aegis...",True,True,True,True,France,NaN,0.99,False,True,US CENTCOM reported destroying more than 80 on...,200.0,200.0,0.0,200.0,NaN,Minimal — most munitions intercepted before re...,0.0,0.0,0.0,0.0,True,False,True,"Coordinated with Hezbollah (Lebanon), Islamic ...",First wave of Shahed-136 loitering munitions a...,NaN,"IDF reported 170 drones, 30 cruise missiles, 1...",https://en.wikipedia.org/wiki/April_2024_Irani...,True,False,False,False,False,False,False,False,False,False,The first wave of Iran's inaugural direct atta...
1,tp1_w02,tp1,2,NaN,Ballistic Missile Wave,NaN,NaN,2024-04-13T23:00:00Z,2024-04-14T02:00:00+0300,2024-04-14T02:30:00+0330,0.0,0.0,1,4.00,240.0,NaN,"120 ballistic missiles including Emad, Ghadr (...",False,True,False,True,True,False,True,False,False,False,False,NaN,NaN,False,True,True,True,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Nevatim Airbase (primary), Ramon Airbase area,...",IL,Israel,False,False,False,True,True,False,NaN,NaN,30.890,34.780,False,IRGC Aerospace Force launch sites in western a...,33.50,50.00,False,True,"Arrow-2, Arrow-3, Aegis BMD / SM-3, Patriot PAC-3",True,True,False,True,NaN,NaN,0.99,True,True,Arrow-2 and Arrow-3 intercepted ballistic miss...,120.0,120.0,0.0,320.0,NaN,Minor damage to Nevatim Airbase (base remained...,0.0,32.0,32.0,0.0,False,False,False,Ballistic missile wave launched directly by IR...,"Second wave of 120 ballistic missiles (Emad, G...",NaN,99% of incoming weapons intercepted; minor dam...,https://en.wikipedia.org/wiki/April_2024_Irani...,True,False,False,False,False,False,False,False,False,False,"The second and final wave of True Promise 1, c..."
2,tp2_w01,tp2,1,NaN,First Ballistic Salvo,2024-10-01T16:30:00Z,IRGC,2024-10-01T16:30:00Z,2024-10-01T19:30:00+0300,2024-10-01T20:00:00+0330,0.0,0.0,1,NaN,NaN,NaN,"Emad, Ghadr-H, Ghadr-F, Kheibar Shekan ballist...",False,True,False,True,True,False,True,False,False,False,False,NaN,NaN,False,True,True,True,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Nevatim Airbase (primary), Tel Nof Airbase, Ha...","IL, JO, PS","Israel, Jordan, Palestine",False,False,False,True,False,False,NaN,NaN,30.890,34.780,False,IRGC Aerospace Force launch sites in western Iran,33.50,50.00,False,True,"Arrow-2, Arrow-3, David's Sling, Aegis BMD / SM-3",True,True,True,True,France,NaN,NaN,True,True,Arrow-2 and Arrow-3 engaged incoming ballistic...,100.0,100.0,0.0,100.0,NaN,Nevatim Airbase: hangar and taxiway damaged (2...,1.0,4.0,5.0,NaN,False,False,False,No proxy coordination — TP2 was a unilateral I...,First wave of approximately 100 ballistic miss...,NaN,IDF reported approximately 200 ballistic missi...,https://en.wikipedia.org/wiki/October_2024_Ira...,True,False,False,False,False,False,False,False,False,False,True Promise 2 opened with a ballistic-missile...
3,tp2_w02,tp2,2,NaN,Second Ballistic Salvo (Fattah-1),NaN,NaN,2024-10-01T16:45:00Z,2024-10-01T19:45:00+0300,2024-10-01T20:15:00+0330,0.0,0.0,1,0.25,15.0,NaN,"Fattah-1 hypersonic missiles, Emad, Kheibar Sh...",False,True,False,True,False,False,True,True,False,False,False,NaN,NaN,False,True,True,True,True,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,Mossad/Unit 8200 HQ at Glilot (north Tel Aviv)...,"IL, JO, PS","Israel, Jordan, Palestine",True,False,False,True,False,False,NaN,NaN,32.150,34.790,False,IRGC Aerospace Force launch sites in western Iran,33.50,50.00,False,True,"Arrow-2, Arrow-3, David's Sling",True,True,False,False,NaN,NaN,NaN,True,True,Most missiles intercepted. Closest impact to M...,100.0,100.0,0.0,200.0,NaN,Missiles landed near Mossad/Unit 8200 HQ (~500...,1.0,4.0,5.0,NaN,False,True,False,NaN,Second wave included Iran's Fattah-1 hypersoni...,NaN,NaN,https://en.wikipedia.org/wiki/October_2024_Ira...,True,False,False,False,True,False,True,False,False,False,The second wave of TP2 targeted the Mossad/Uni...
4,tp3_w01,tp3,1,NaN,NaN,2025-06-13T18:30:00Z,IRGC,2025-06-13T18:30:00Z,2025-06-13T21:30:00+0300,2025-06-14T00:00:00+0330,0.0,0.0,1,NaN,NaN,NaN,"~100 ballistic missiles, drones",True,True,False,True,True,False,False,False,True,False,True,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Military centers, air bases",IL,Israel,True,False,False,True,False,False,NaN,NaN,31.660,34.780,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,100.0,100.0,0.0,NaN,NaN,Serious damage to sensitive military centers i...,NaN,NaN,NaN,NaN,True,True,False,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,False,False,The opening salvo of the Twelve-Day War. Launc...
5,tp3_w02,tp3,2,NaN,NaN,2025-06-13T19:30:00Z,IRGC,2025-06-13T19:30:00Z,2025-06-13T22:30:00+0300,2025-06-14T01:00:00+0330,0.0,0.0,1,1.00,NaN,NaN,"Ballistic missiles, drones",True,True,False,True,True,False,False,False,True,False,True,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Haifa, Galilee",IL,Israel,False,False,True,False,True,False,NaN,NaN,32.835,35.250,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,NaN,NaN,0.0,NaN,NaN,State of emergency declared across Israel,NaN,NaN,NaN,NaN,False,False,False,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,False,False,False,The second wave shifted targeting to Haifa and...
6,tp3_w03,tp3,3,يا علي بن أبي طالب,Ya Ali ibn Abi Talib,2025-06-14T15:00:00Z,IRGC,2025-06-14T15:00:00Z,2025-06-14T18:00:00+0300,2025-06-14T20:30:00+0330,5.0,5.0,2,19.50,NaN,NaN,Dozens of missiles and drones,True,True,False,True,True,False,False,False,True,False,True,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,Occupied territories — penetrated multiple def...,IL,Israel,True,False,False,False,False,False,NaN,NaN,32.070,34.770,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,False,False,False,A significant wave that Iran claimed penetrate...
7,tp3_w04,tp3,4,NaN,NaN,2025-06-14T19:00:00Z,IRGC,2025-06-14T19:00:00Z,2025-06-14T22:00:00+0300,2025-06-15T00:30:00+0330,0.0,0.0,2,4.00,NaN,NaN,Ballistic missiles,False,True,False,True,True,False,False,False,False,False,NaN,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Tel Aviv, Haifa, other cities",IL,Israel,True,False,True,False,False,False,NaN,NaN,32.445,34.885,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,NaN,NaN,0.0,NaN,NaN,Continued escalation — strikes on urban areas,NaN,NaN,NaN,NaN,False,False,False,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,False,True,False,A multi-city bombardment targeting both Tel Av...
8,tp3_w05,tp3,5,NaN,NaN,2025-06-15T05:00:00Z,IRGC,2025-06-15T05:00:00Z,2025-06-15T08:00:00+0300,2025-06-15T10:30:00+0330,5.0,5.0,3,10.00,NaN,NaN,Ballistic missiles,False,True,False,True,True,False,False,False,False,False,NaN,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Haifa oil refinery, military targets",IL,Israel,False,False,True,False,False,False,NaN,NaN,32.820,35.000,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,NaN,NaN,0.0,NaN,NaN,Haifa oil refinery directly hit and shut down,NaN,NaN,NaN,NaN,False,False,True,Houthis joined from Yemen with coordinated lau...,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,True,False,False,This wave marked the first targeting of critic...
9,tp3_w06,tp3,6,NaN,NaN,2025-06-15T15:00:00Z,IRGC,2025-06-15T15:00:00Z,2025-06-15T18:00:00+0300,2025-06-15T20:30:00+0330,5.0,5.0,3,10.00,NaN,NaN,Missiles,False,True,False,True,True,False,False,False,False,False,NaN,NaN,NaN,NaN,True,False,False,False,NaN,False,NaN,NaN,NaN,NaN,NaN,True,False,"Israeli C2 centers, Haifa, Tel Aviv; Bat Yam s...",IL,Israel,True,False,True,False,False,False,NaN,NaN,32.445,34.885,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,NaN,NaN,NaN,True,True,NaN,NaN,NaN,0.0,NaN,NaN,Bat Yam residential building struck — 9 killed...,9.0,200.0,9.0,0.0,False,False,True,Coordinated Houthi/Yemen simultaneous launch,NaN,NaN,NaN,NaN,False,False,False,False,True,False,False,False,True,False,A wave targeting Israeli command and control c...

In [16]:
dfw.describe().T

,count,mean,std,min,25%,50%,75%,max
wave_number,55.0,12.618182,8.168347,1.00,5.50,12.000,19.000,29.00
solar_phase_launch_site,44.0,2.613636,2.461007,0.00,0.00,4.000,5.000,5.00
solar_phase_target,44.0,2.568182,2.453263,0.00,0.00,3.000,5.000,5.00
conflict_day,55.0,4.927273,3.143804,1.00,2.00,4.000,8.000,12.00
hours_since_last_wave,37.0,7.824324,5.709430,0.25,4.00,6.000,10.000,23.00
time_between_waves_minutes,4.0,363.750000,348.218681,15.00,183.75,300.000,480.000,840.00
wave_duration_minutes,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shahed_107_used,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shahed_129_used,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cluster_submunition_count,6.0,30.000000,24.494897,20.00,20.00,20.000,20.000,80.00
cluster_submunition_explosive_kg,6.0,2.500000,0.000000,2.50,2.50,2.500,2.500,2.50
cluster_dispersal_radius_km,6.0,9.333333,3.265986,8.00,8.00,8.000,8.000,16.00
target_lat,50.0,31.695896,1.268145,25.92,31.63,32.070,32.445,32.85
target_lon,50.0,36.248672,4.128520,34.77,34.78,34.885,35.015,50.59
launch_site_lat,55.0,33.879091,1.091291,26.50,33.50,34.310,34.310,34.31
launch_site_lon,55.0,47.880909,1.374311,47.07,47.07,47.070,48.500,53.00
estimated_intercept_count,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
estimated_intercept_rate,2.0,0.990000,0.000000,0.99,0.99,0.990,0.990,0.99
estimated_munitions_count,15.0,62.866667,51.814045,8.00,30.50,40.000,100.000,200.00
munitions_targeting_israel,13.0,81.076923,70.177705,8.00,37.00,45.000,100.000,230.00
munitions_targeting_us_bases,31.0,11.419355,42.445082,0.00,0.00,0.000,0.000,230.00
cumulative_total,6.0,148.333333,112.101145,35.00,51.25,150.000,200.000,320.00
small_number_of_missiles,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fatalities,34.0,0.852941,2.258081,0.00,0.00,0.000,0.000,9.00
injuries,33.0,10.181818,35.444018,0.00,0.00,0.000,4.000,200.00
civilian_casualties,33.0,2.000000,5.926635,0.00,0.00,0.000,0.000,32.00
military_casualties,30.0,0.000000,0.000000,0.00,0.00,0.000,0.000,0.00

In [18]:
len(dfw)

55

In [20]:
!ls

data_dictionary.csv	     international_reactions.parquet  waves.csv
international_reactions.csv  sample_data		      waves.parquet

In [21]:
!head waves.csv

wave_uid,operation,wave_number,wave_codename_farsi,wave_codename_english,announced_utc,announcement_source,probable_launch_time,launch_time_israel,launch_time_iran,solar_phase_launch_site,solar_phase_target,conflict_day,hours_since_last_wave,time_between_waves_minutes,wave_duration_minutes,payload,drones_used,ballistic_missiles_used,cruise_missiles_used,emad_used,ghadr_used,sejjil_used,kheibar_shekan_used,fattah_used,shahed_136_used,shahed_238_used,shahed_131_used,shahed_107_used,shahed_129_used,mohajer_6_used,bm_liquid_fueled,bm_solid_fueled,bm_marv_equipped,bm_hypersonic,bm_cluster_warhead,cluster_munitions,cluster_warhead_confirmed,cluster_carrier_missile,cluster_submunition_count,cluster_submunition_explosive_kg,cluster_dispersal_radius_km,israel_targeted,us_bases_targeted,targets,landings_countries_iso,landings_countries,targeted_tel_aviv,targeted_jerusalem,targeted_haifa,targeted_negev_beersheba,targeted_northern_periphery,targeted_eilat,us_bases_list,us_naval_vessels_list,target_lat,target_lon,target_generic_location,launch_site_description,launch_site_lat,launch_site_lon,launch_site_generic_location,intercepted,interception_systems,intercepted_by_israel,intercepted_by_us,intercepted_by_uk,intercepted_by_jordan,intercepted_by_other,estimated_intercept_count,estimated_intercept_rate,exoatmospheric_interception,endoatmospheric_interception,interception_report,estimated_munitions_count,munitions_targeting_israel,munitions_targeting_us_bases,cumulative_total,small_number_of_missiles,damage,fatalities,injuries,civilian_casualties,military_casualties,new_country_targeted,new_weapon_first_use,proxy_involvement,proxy_description,description,iranian_media_claims,idf_statement,source_urls,target_iaf_base,target_us_base,target_naval_base,target_naval_vessel,target_government_c2,target_military_industrial,target_intelligence,target_civilian_infrastructure,target_civilian_area,target_diplomatic,narrative
tp1_w01,tp1,1,,Drone/Cruise Missile Wave,2024-04-13T19:00:00Z,IRGC,2024-04-13T19:00:00Z,2024-04-13T22:00:00+0300,2024-04-13T22:30:00+0330,0.0,0.0,1,,,,170 Shahed-136 loitering munitions and 30 Paveh cruise missiles,True,False,True,False,False,False,False,False,True,False,,,,,False,False,False,False,,False,,,,,,True,False,"Nevatim Airbase, sites in Negev desert and Israeli-occupied Golan Heights",IL,Israel,False,False,False,True,True,False,,,30.89,34.78,False,Multiple sites across Iran; Shahed drones also launched from Iraq and Yemen by proxies,33.0,52.0,False,True,"Iron Dome, David's Sling, Patriot PAC-3, Aegis BMD / SM-3",True,True,True,True,France,,0.99,False,True,US CENTCOM reported destroying more than 80 one-way attack drones and at least 6 ballistic missiles. Jordan and UK RAF also intercepted drones over Jordanian airspace. France contributed to interception efforts.,200.0,200.0,0.0,200.0,,Minimal — most munitions intercepted before reaching Israeli airspace,0.0,0.0,0.0,0.0,True,False,True,"Coordinated with Hezbollah (Lebanon), Islamic Resistance in Iraq, and Ansar Allah (Houthis, Yemen). Drones and rockets also launched from Iraqi, Yemeni, and Lebanese territory.","First wave of Shahed-136 loitering munitions and Paveh cruise missiles intended to saturate Israeli air defenses (Iron Dome, David's Sling) ahead of the ballistic missile wave. Drones launched several hours before ballistic missiles due to slower flight speed (~185 km/h for Shahed-136 vs minutes for ballistic missiles).",,"IDF reported 170 drones, 30 cruise missiles, 120 ballistic missiles launched; 99% interception rate","https://en.wikipedia.org/wiki/April_2024_Iranian_strikes_on_Israel, https://www.aljazeera.com/news/2024/4/14/true-promise-why-and-how-did-iran-launch-a-historic-attack-on-israel",True,False,False,False,False,False,False,False,False,False,"The first wave of Iran's inaugural direct attack on Israel. Launched on the night of 13 April 2024, this wave comprised a large combined salvo of Shahed-136 drones, ballistic missiles, and cruise missiles targeting Nevatim Airbase and sites across the Negev desert and Israeli-occupied Golan Heights. The attack was widely telegraphed in advance, giving Israel, the US, UK, France, and Jordan time to coordinate a multilayered defensive response. The overwhelming majority of munitions were intercepted."
tp1_w02,tp1,2,,Ballistic Missile Wave,,,2024-04-13T23:00:00Z,2024-04-14T02:00:00+0300,2024-04-14T02:30:00+0330,0.0,0.0,1,4.0,240.0,,"120 ballistic missiles including Emad, Ghadr (Ghadr-S/H/F variants), Kheibar Shekan, possibly Shahab-3B",False,True,False,True,True,False,True,False,False,False,False,,,False,True,True,True,False,,False,,,,,,True,False,"Nevatim Airbase (primary), Ramon Airbase area, sites in Negev desert and Golan Heights",IL,Israel,False,False,False,True,True,False,,,30.89,34.78,False,IRGC Aerospace Force launch sites in western and central Iran,33.5,50.0,False,True,"Arrow-2, Arrow-3, Aegis BMD / SM-3, Patriot PAC-3",True,True,False,True,,,0.99,True,True,"Arrow-2 and Arrow-3 intercepted ballistic missiles, with Arrow-3 performing exoatmospheric interceptions. SM-3 from US Navy destroyers was used in combat for the first time. A small number of ballistic missiles struck Nevatim Airbase causing minor damage; the base remained fully operational.",120.0,120.0,0.0,320.0,,Minor damage to Nevatim Airbase (base remained operational); debris fell in Arad region,0.0,32.0,32.0,0.0,False,False,False,Ballistic missile wave launched directly by IRGC Aerospace Force from Iranian territory,"Second wave of 120 ballistic missiles (Emad, Ghadr, Kheibar Shekan, possibly Shahab-3B) timed to arrive after drone wave had engaged Israeli air defense systems. Ballistic missiles launched later but arrived within minutes due to much higher velocity. Several missiles struck Nevatim Airbase area causing minor damage.",,99% of incoming weapons intercepted; minor damage to Nevatim Airbase,"https://en.wikipedia.org/wiki/April_2024_Iranian_strikes_on_Israel, https://besacenter.org/operation-true-promise-irans-missile-attack-on-israel/, https://www.iranwatch.org/our-publications/articles-reports/irans-missile-attack-against-israel",True,False,False,False,False,False,False,False,False,False,"The second and final wave of True Promise 1, continuing the bombardment of Nevatim Airbase and the Ramon Airbase area in the Negev. This wave followed the initial drone/missile salvo by several hours, with ballistic missiles arriving after the slower drones. Minor damage was reported at Nevatim. The combined two-wave attack involved approximately 320 munitions — the largest single aerial assault in the region's history at the time. Israel's multi-tier defense (Arrow, David's Sling, Iron Dome) achieved a near-total interception rate with coalition support."
tp2_w01,tp2,1,,First Ballistic Salvo,2024-10-01T16:30:00Z,IRGC,2024-10-01T16:30:00Z,2024-10-01T19:30:00+0300,2024-10-01T20:00:00+0330,0.0,0.0,1,,,,"Emad, Ghadr-H, Ghadr-F, Kheibar Shekan ballistic missiles",False,True,False,True,True,False,True,False,False,False,False,,,False,True,True,True,False,,False,,,,,,True,False,"Nevatim Airbase (primary), Tel Nof Airbase, Hatzerim Airbase","IL, JO, PS","Israel, Jordan, Palestine",False,False,False,True,False,False,,,30.89,34.78,False,IRGC Aerospace Force launch sites in western Iran,33.5,50.0,False,True,"Arrow-2, Arrow-3, David's Sling, Aegis BMD / SM-3",True,True,True,True,France,,,True,True,"Arrow-2 and Arrow-3 engaged incoming ballistic missiles. US Navy destroyers fired SM-3 interceptors. Despite interceptions, 20-32 missiles struck Nevatim Airbase area and 3 struck Tel Nof area per satellite analysis.",100.0,100.0,0.0,100.0,,Nevatim Airbase: hangar and taxiway damaged (20-32 impacts confirmed by satellite); Tel Nof Airbase: several impacts; Gedera: school building hit,1.0,4.0,5.0,,False,False,False,No proxy coordination — TP2 was a unilateral IRGC operation unlike the multi-front TP1,"First wave of approximately 100 ballistic missiles targeting Israeli military airbases and intelligence facilities. Unlike TP1, no drones or cruise missiles were used — Iran opted for a purely ballistic approach to minimize warning time. Missiles included Emad, Ghadr-H, Ghadr-F, and Kheibar Shekan. Iran gave only a few hours' warning to Arab states (compared to 72 hours in TP1).",,IDF reported approximately 200 ballistic missiles fired in two waves,"https://en.wikipedia.org/wiki/October_2024_Iranian_strikes_on_Israel, https://www.npr.org/2024/10/04/nx-s1-5140058/satellite-images-dozens-iranian-missiles-struck-near-israeli-air-base",True,False,False,False,False,False,False,False,False,False,"True Promise 2 opened with a ballistic-missile-only salvo on 1 October 2024, a significant tactical shift from TP1's mixed drone/missile approach. Approximately 180–200 Emad and Ghadr ballistic missiles targeted Nevatim, Tel Nof, and Hatzerim airbases. The absence of slow-moving drones meant defenders had far less warning time. Some missiles penetrated Israeli defenses, impacting near Nevatim."
tp2_w02,tp2,2,,Second Ballistic Salvo (Fattah-1),,,2024-10-01T16:45:00Z,2024-10-01T19:45:00+0300,2024-10-01T20:15:00+0330,0.0,0.0,1,0.25,15.0,,"Fattah-1 hypersonic missiles, Emad, Kheibar Shekan ballistic missiles",False,True,False,True,False,False,True,True,False,False,False,,,False,True,True,True,True,,False,,,,,,True,False,"Mossad/Unit 8200 HQ at Glilot (north Tel Aviv), Nevatim Airbase, Tel Nof Airbase","IL, JO, PS","Israel, Jordan, Palestine",True,False,False,True,False,False,,,32.15,34.79,False,IRGC Aerospace Force launch sites in western Iran,33.5,50.0,False,True,"Arrow-2, Arrow-3, David's Sling",True,True,False,False,,,,True,True,"Most missiles intercepted. Closest impact to Mossad HQ was approximately 500m. Fattah-1 hypersonic missile performance debated — Israel claimed successful interception, Iran claimed successful penetration.",100.0,100.0,0.0,200.0,,Missiles landed near Mossad/Unit 8200 HQ (~500m); homes and restaurant damaged in north Tel Aviv area; additional impacts at Nevatim and Tel Nof,1.0,4.0,5.0,,False,True,False,,"Second wave included Iran's Fattah-1 hypersonic missile in its first confirmed combat use, alongside additional Emad and Kheibar Shekan missiles. This wave targeted the Mossad/Unit 8200 headquarters complex at Glilot near Tel Aviv in addition to the airbases. Satellite imagery later showed missiles landing approximately 500m from the Mossad complex.",,,"https://en.wikipedia.org/wiki/October_2024_Iranian_strikes_on_Israel, https://english.iswnews.com/36492/operation-true-promise-ii-review-on-irans-missile-attack-on-israeli-regime/, https://defensemirror.com/news/37814/Iran_Releases_Info_on_Missiles_Used_in____Operation_True_Promise_II____against_Israel",True,False,False,False,True,False,True,False,False,False,"The second wave of TP2 targeted the Mossad/Unit 8200 headquarters complex at Glilot north of Tel Aviv, marking the first Iranian strike aimed at Israeli intelligence infrastructure. Nevatim and Tel Nof airbases were also targeted again. Two fatalities were reported — the first confirmed deaths from a direct Iranian strike on Israel. The all-ballistic approach of TP2 demonstrated Iran's evolving understanding that fast-moving missiles were more effective at penetrating Israeli defenses than the mixed salvos of TP1."
tp3_w01,tp3,1,,,2025-06-13T18:30:00Z,IRGC,2025-06-13T18:30:00Z,2025-06-13T21:30:00+0300,2025-06-14T00:00:00+0330,0.0,0.0,1,,,,"~100 ballistic missiles, drones",True,True,False,True,True,False,False,False,True,False,True,,,,True,False,False,False,,False,,,,,,True,False,"Military centers, air bases",IL,Israel,True,False,False,True,False,False,,,31.66,34.78,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,,,,True,True,,100.0,100.0,0.0,,,Serious damage to sensitive military centers in Tel Aviv area,,,,,True,True,False,,,,,,True,False,False,False,False,False,False,False,False,False,"The opening salvo of the Twelve-Day War. Launched on 13 June 2025, this wave targeted military centres and air bases across Israel with ballistic missiles. It marked the beginning of Iran's most sustained aerial campaign to date, which would continue for 22 waves over 12 days."
tp3_w02,tp3,2,,,2025-06-13T19:30:00Z,IRGC,2025-06-13T19:30:00Z,2025-06-13T22:30:00+0300,2025-06-14T01:00:00+0330,0.0,0.0,1,1.0,,,"Ballistic missiles, drones",True,True,False,True,True,False,False,False,True,False,True,,,,True,False,False,False,,False,,,,,,True,False,"Haifa, Galilee",IL,Israel,False,False,True,False,True,False,,,32.835,35.25,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,,,,True,True,,,,0.0,,,State of emergency declared across Israel,,,,,False,False,False,,,,,,False,False,False,False,False,False,False,False,False,False,"The second wave shifted targeting to Haifa and the Galilee region in northern Israel, expanding the geographic scope beyond the southern airbases that dominated TP1 and TP2. Ballistic missiles were used alongside drone swarms for the first time in TP3."
tp3_w03,tp3,3,يا علي بن أبي طالب,Ya Ali ibn Abi Talib,2025-06-14T15:00:00Z,IRGC,2025-06-14T15:00:00Z,2025-06-14T18:00:00+0300,2025-06-14T20:30:00+0330,5.0,5.0,2,19.5,,,Dozens of missiles and drones,True,True,False,True,True,False,False,False,True,False,True,,,,True,False,False,False,,False,,,,,,True,False,Occupied territories — penetrated multiple defense layers,IL,Israel,True,False,False,False,False,False,,,32.07,34.77,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,,,,True,True,,,,0.0,,,,,,,,False,False,False,,,,,,False,False,False,False,False,False,False,False,False,False,A significant wave that Iran claimed penetrated multiple Israeli defense layers and struck targets in the occupied territories. This represented an escalation in Iranian rhetoric about the effectiveness of their strikes.
tp3_w04,tp3,4,,,2025-06-14T19:00:00Z,IRGC,2025-06-14T19:00:00Z,2025-06-14T22:00:00+0300,2025-06-15T00:30:00+0330,0.0,0.0,2,4.0,,,Ballistic missiles,False,True,False,True,True,False,False,False,False,False,,,,,True,False,False,False,,False,,,,,,True,False,"Tel Aviv, Haifa, other cities",IL,Israel,True,False,True,False,False,False,,,32.445,34.885,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,,,,True,True,,,,0.0,,,Continued escalation — strikes on urban areas,,,,,False,False,False,,,,,,False,False,False,False,False,False,False,False,True,False,"A multi-city bombardment targeting both Tel Aviv and Haifa simultaneously, forcing Israel to defend across a wide geographic front. This dual-axis approach became a hallmark of TP3's middle waves."
tp3_w05,tp3,5,,,2025-06-15T05:00:00Z,IRGC,2025-06-15T05:00:00Z,2025-06-15T08:00:00+0300,2025-06-15T10:30:00+0330,5.0,5.0,3,10.0,,,Ballistic missiles,False,True,False,True,True,False,False,False,False,False,,,,,True,False,False,False,,False,,,,,,True,False,"Haifa oil refinery, military targets",IL,Israel,False,False,True,False,False,False,,,32.82,35.0,True,Western Iran,34.31,47.07,True,True,"Arrow-2, Arrow-3, THAAD, Iron Dome",True,True,False,False,,,,True,True,,,,0.0,,,Haifa oil refinery directly hit and shut down,,,,,False,False,True,Houthis joined from Yemen with coordinated launches,,,,,False,False,False,False,False,False,False,True,False,False,This wave marked the first targeting of critical civilian infrastructure — specifically the Haifa oil refinery — alongside military targets. The expansion to economic infrastructure signalled an escalation in Iranian targeting doctrine.

In [22]:
dfw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Columns: 103 entries, wave_uid to narrative
dtypes: bool(14), float64(25), int64(2), object(62)
memory usage: 39.1+ KB

In [23]:
dfw.dtypes

wave_uid                          object
operation                         object
wave_number                        int64
wave_codename_farsi               object
wave_codename_english             object
                                   ...
target_intelligence                 bool
target_civilian_infrastructure      bool
target_civilian_area                bool
target_diplomatic                   bool
narrative                         object
Length: 103, dtype: object

In [24]:
list(dfw.columns)

['wave_uid',
 'operation',
 'wave_number',
 'wave_codename_farsi',
 'wave_codename_english',
 'announced_utc',
 'announcement_source',
 'probable_launch_time',
 'launch_time_israel',
 'launch_time_iran',
 'solar_phase_launch_site',
 'solar_phase_target',
 'conflict_day',
 'hours_since_last_wave',
 'time_between_waves_minutes',
 'wave_duration_minutes',
 'payload',
 'drones_used',
 'ballistic_missiles_used',
 'cruise_missiles_used',
 'emad_used',
 'ghadr_used',
 'sejjil_used',
 'kheibar_shekan_used',
 'fattah_used',
 'shahed_136_used',
 'shahed_238_used',
 'shahed_131_used',
 'shahed_107_used',
 'shahed_129_used',
 'mohajer_6_used',
 'bm_liquid_fueled',
 'bm_solid_fueled',
 'bm_marv_equipped',
 'bm_hypersonic',
 'bm_cluster_warhead',
 'cluster_munitions',
 'cluster_warhead_confirmed',
 'cluster_carrier_missile',
 'cluster_submunition_count',
 'cluster_submunition_explosive_kg',
 'cluster_dispersal_radius_km',
 'israel_targeted',
 'us_bases_targeted',
 'targets',
 'landings_countries_iso',
 'landings_countries',
 'targeted_tel_aviv',
 'targeted_jerusalem',
 'targeted_haifa',
 'targeted_negev_beersheba',
 'targeted_northern_periphery',
 'targeted_eilat',
 'us_bases_list',
 'us_naval_vessels_list',
 'target_lat',
 'target_lon',
 'target_generic_location',
 'launch_site_description',
 'launch_site_lat',
 'launch_site_lon',
 'launch_site_generic_location',
 'intercepted',
 'interception_systems',
 'intercepted_by_israel',
 'intercepted_by_us',
 'intercepted_by_uk',
 'intercepted_by_jordan',
 'intercepted_by_other',
 'estimated_intercept_count',
 'estimated_intercept_rate',
 'exoatmospheric_interception',
 'endoatmospheric_interception',
 'interception_report',
 'estimated_munitions_count',
 'munitions_targeting_israel',
 'munitions_targeting_us_bases',
 'cumulative_total',
 'small_number_of_missiles',
 'damage',
 'fatalities',
 'injuries',
 'civilian_casualties',
 'military_casualties',
 'new_country_targeted',
 'new_weapon_first_use',
 'proxy_involvement',
 'proxy_description',
 'description',
 'iranian_media_claims',
 'idf_statement',
 'source_urls',
 'target_iaf_base',
 'target_us_base',
 'target_naval_base',
 'target_naval_vessel',
 'target_government_c2',
 'target_military_industrial',
 'target_intelligence',
 'target_civilian_infrastructure',
 'target_civilian_area',
 'target_diplomatic',
 'narrative']

# Dataset Simplificado

In [ ]:
import pandas as pd
import sqlite3
import re

# ==========================================
# 1. CARREGAR DATASET
# ==========================================

arquivo = "waves.csv"

df = pd.read_csv(arquivo)

print("Linhas:", len(df))
print("Colunas:", len(df.columns))


# ==========================================
# 2. PADRONIZAR NOMES DAS COLUNAS
# ==========================================

def normalize_column(col):

    col = col.strip().lower()
    col = re.sub(r"[^\w\s]", "", col)
    col = re.sub(r"\s+", "_", col)
    col = re.sub(r"_+", "_", col)

    return col

df.columns = [normalize_column(c) for c in df.columns]


# ==========================================
# 3. LIMPAR VALORES NULOS
# ==========================================

null_values = [
    "", "none", "null", "nan", "na", "n/a", "unknown"
]

df.replace(null_values, pd.NA, inplace=True)


# ==========================================
# 4. LIMPAR ESPAÇOS
# ==========================================

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()


# ==========================================
# 5. CRIAR DATA DO EVENTO
# ==========================================

if "anunciado_utc" in df.columns:

    df["data_evento"] = pd.to_datetime(
        df["anunciado_utc"], errors="coerce"
    )

elif "horario_provavel_de_lancamento" in df.columns:

    df["data_evento"] = pd.to_datetime(
        df["horario_provavel_de_lancamento"],
        errors="coerce"
    )

else:

    df["data_evento"] = pd.NaT


# ==========================================
# 6. PADRONIZAR COORDENADAS
# ==========================================

df["latitude"] = pd.to_numeric(
    df.get("target_lat"), errors="coerce"
)

df["longitude"] = pd.to_numeric(
    df.get("target_lon"), errors="coerce"
)


# ==========================================
# 7. IDENTIFICAR PAÍS
# ==========================================

if "paises_de_impacto" in df.columns:

    df["pais"] = df["paises_de_impacto"]

elif "landings_countries_iso" in df.columns:

    df["pais"] = df["landings_countries_iso"]

else:

    df["pais"] = None


# ==========================================
# 8. DATASET SIMPLES PARA ANÁLISE
# ==========================================

colunas_analise = [

    "id_da_onda",
    "operacao",
    "numero_da_onda",

    "data_evento",

    "pais",

    "latitude",
    "longitude",

    "drones_utilizados",
    "misseis_balisticos_utilizados",
    "misseis_de_cruzeiro_utilizados",

    "estimated_munitions_count",
    "estimated_intercept_rate",

    "danos",
    "mortes",
    "feridos",

    "interceptado"

]

df_analise = df[colunas_analise]

df_analise = df_analise.dropna(
    subset=["latitude", "longitude"]
)

df_analise.to_csv(
    "waves_dataset_geo_analise.csv",
    index=False
)

print("CSV de análise criado")


# ==========================================
# 9. CONSTRUIR DATASET CIENTÍFICO
# ==========================================

# ---------- EVENTS ----------

events = df[[
    "id_da_onda",
    "operacao",
    "numero_da_onda",
    "data_evento"
]].copy()

events.rename(columns={
    "id_da_onda": "event_id",
    "operacao": "operation",
    "numero_da_onda": "wave_number"
}, inplace=True)


# ---------- LOCATIONS ----------

locations = df[[
    "id_da_onda",
    "pais",
    "latitude",
    "longitude"
]].copy()

locations.rename(columns={
    "id_da_onda": "event_id",
    "pais": "country"
}, inplace=True)


# ---------- WEAPONS ----------

weapons = df[[
    "id_da_onda",
    "drones_utilizados",
    "misseis_balisticos_utilizados",
    "misseis_de_cruzeiro_utilizados",
    "estimated_munitions_count"
]].copy()

weapons.rename(columns={
    "id_da_onda": "event_id",
    "drones_utilizados": "drones",
    "misseis_balisticos_utilizados": "ballistic_missiles",
    "misseis_de_cruzeiro_utilizados": "cruise_missiles",
    "estimated_munitions_count": "total_munitions"
}, inplace=True)


# ---------- CASUALTIES ----------

casualties = df[[
    "id_da_onda",
    "mortes",
    "feridos"
]].copy()

casualties.rename(columns={
    "id_da_onda": "event_id",
    "mortes": "fatalities",
    "feridos": "injuries"
}, inplace=True)


# ---------- INTERCEPTIONS ----------

interceptions = df[[
    "id_da_onda",
    "interceptado",
    "estimated_intercept_rate"
]].copy()

interceptions.rename(columns={
    "id_da_onda": "event_id",
    "interceptado": "intercepted",
    "estimated_intercept_rate": "intercept_rate"
}, inplace=True)


# ==========================================
# 10. SALVAR BANCO CIENTÍFICO
# ==========================================

conn = sqlite3.connect(
    "geopolitics_conflict_dataset.sqlite"
)

events.to_sql("events", conn,
              if_exists="replace", index=False)

locations.to_sql("locations", conn,
                 if_exists="replace", index=False)

weapons.to_sql("weapons", conn,
               if_exists="replace", index=False)

casualties.to_sql("casualties", conn,
                  if_exists="replace", index=False)

interceptions.to_sql("interceptions", conn,
                     if_exists="replace", index=False)

conn.close()

print("Banco científico criado")